name: EXD Files
on:
  push:
    branches: [main, dev]
    paths-ignore:
      - 'README.md'

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Retrieve cache
        id: retrieve-cache
        uses: actions/cache@v4
        with:
          path: data
          key: exd-files-data

      - name: Run downloader
        uses: ./
        with:
          output-path: data
          regex: '^sqpack\/ffxiv\/0a0000\..+$'
