name: Movies
on:
  push:
    branches: [main, dev]
    paths-ignore:
      - 'README.md'

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Run downloader
        uses: ./
        with:
          output-path: data
          regex: '^movie\/.+$'
