name: Sqpack-040000
on:
  push:
    branches: [main]
    paths-ignore:
      - 'README.md'

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run downloader
        id: downloader
        uses: ./
        with:
          output-path: ./data
          file-regex: '^sqpack\/ffxiv\/040000\..+$'
