name: Update Lookup Tables
on:
  push:
    branches: [main, dev]
    paths-ignore:
      - 'README.md'
    workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0'

      - name: Restore
        run: |
          dotnet restore

      - name: Build
        run: |
          dotnet publish -c Release --no-restore

      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: FFXIVDownloader.Command/bin/Release/net9.0/publish
          if-no-files-found: error

  download:
    name: Download LUTs
    runs-on: ubuntu-latest
    needs: build

    strategy:
      fail-fast: false
      matrix:
        slugs:
          - 2b5cbc63 # boot
          - 4e9a232b # ffxiv
          - 6b936f08 # ex1
          - f29a3eb2 # ex2
          - 859d0e24 # ex3
          - 1bf99b87 # ex4
          - 6cfeab11 # ex5

          - de199059 # Korea ffxiv
          - 573d8c07 # Korea ex1
          - ce34ddbd # Korea ex2
          - b933ed2b # Korea ex3
          - '27577888' # Korea ex4
          - 5050481e # Korea ex5

          - c38effbc # China ffxiv
          - 77420d17 # China ex1
          - ee4b5cad # China ex2
          - 994c6c3b # China ex3
          - 0728f998 # China ex4
          - 702fc90e # China ex5

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # - name: Setup .NET
      #   uses: actions/setup-dotnet@v4
      #   with:
      #     dotnet-version: '9.0'

      - name: Download Build
        uses: actions/download-artifact@v4
        with:
          name: build

      - name: Retrieve LUTs
        run: |
          build/FFXIVDownloader.Command --verbose lut -s "${{matrix.slug}}" -o "luts/${{matrix.slug}}" -c Brotli

      - name: Calculate CLUTs
        run: |
          build/FFXIVDownloader.Command --verbose --debug clut -s "${{matrix.slug}}" -b "luts/${{matrix.slug}}" -o "cluts/${{matrix.slug}}" -c Brotli

    - name: Commit Changes
      id: commit
      continue-on-error: true
      run: |
        git config user.name github-actions[bot]
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com
        git add .
        git commit -m "Update Lookups for ${{matrix.slug}}" --author="${{github.actor}} <${{github.actor}}@users.noreply.github.com>"

    - name: Fetch and Rebase
      id: fetch
      continue-on-error: true
      if: ${{steps.commit.conclusion == 'success'}}
      run: |
        git fetch origin
        git rebase -X theirs origin/${{github.ref}}

    - name: Push Changes
      if: ${{steps.fetch.conclusion == 'success'}}
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        branch: ${{github.ref}}
